// The whole build: write apps/web/config.js from the environment.
//
// The site has no bundler and does not want one. What it cannot do by
// itself is know which Supabase project it is talking to, because that
// differs between a preview deployment and production and must not be
// committed. So this reads two environment variables and writes one file.
//
// Run by Vercel via vercel.json. Locally:
//
//   SUPABASE_URL=... SUPABASE_ANON_KEY=... node tool/build-web.mjs
//
// With neither set it writes nothing and says so, and the site falls back
// to its fixtures — which is the right behaviour for a preview someone
// opened before configuring anything, and for `git clone && open`.

import { writeFileSync, existsSync, unlinkSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const target = join(root, "apps", "web", "config.js");

const url = (process.env.SUPABASE_URL || "").trim();
const key = (process.env.SUPABASE_ANON_KEY || "").trim();

if (!url || !key) {
  if (existsSync(target)) unlinkSync(target);
  console.log("no SUPABASE_URL / SUPABASE_ANON_KEY — building the demo, with fixtures and no backend");
  process.exit(0);
}

// The one thing that must never happen here. A service-role key bypasses
// every row-level security policy in supabase/migrations, and this file is
// served to every visitor. The two key types are told apart by the `role`
// claim in the JWT payload, which is the middle segment.
const role = readRole(key);
if (role && role !== "anon") {
  console.error(
    `\nSUPABASE_ANON_KEY holds a "${role}" key, not an anon key.\n\n` +
    "That key bypasses row-level security and config.js is public. Refusing\n" +
    "to write it. Copy the anon/public key from the project's API settings.\n",
  );
  process.exit(1);
}
if (!/^https:\/\/[^\s/]+\.supabase\.(co|in)$/.test(url) && !url.startsWith("http://localhost")) {
  console.error(`\nSUPABASE_URL does not look like a project URL: ${url}\n`);
  process.exit(1);
}

writeFileSync(target, `// Generated by tool/build-web.mjs. Do not edit, do not commit.
//
// The anon key is public by design: it identifies the project and grants
// nothing on its own. Every row it reaches is reached through the policies
// in supabase/migrations, which is where access is actually decided.
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`);

console.log(`wrote apps/web/config.js → ${url}`);

function readRole(jwt) {
  try {
    const [, payload] = jwt.split(".");
    return JSON.parse(Buffer.from(payload, "base64url").toString()).role || "";
  } catch {
    // Supabase has more than one key format. An unreadable key is not
    // proof of anything, so it is not a reason to fail the build — the
    // check above is a guard against an obvious mistake, not a validator.
    return "";
  }
}
