// The whole build: write apps/web/config.js from the environment.
//
// The site has no bundler and does not want one. What it cannot do by
// itself is know which Supabase project it is talking to, because that
// differs between a preview deployment and production and must not be
// committed. So this reads two environment variables and writes one file.
//
// Run by Vercel via vercel.json. Locally:
//
//   SUPABASE_URL=... SUPABASE_ANON_KEY=... node tool/build-web.mjs
//
// With neither set it writes nothing and says so, and the site falls back
// to its fixtures — which is the right behaviour for a preview someone
// opened before configuring anything, and for `git clone && open`.

import { writeFileSync, existsSync, unlinkSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const target = join(root, "apps", "web", "config.js");

// Vercel's Supabase integration writes NEXT_PUBLIC_SUPABASE_URL and does
// not write a plain SUPABASE_URL, so reading only the plain name builds
// the demo on a correctly configured project and says nothing about why.
// The NEXT_PUBLIC_ prefix is a Next.js convention this site does not use;
// it is accepted because that is the name the integration produces.
const url = first("SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_URL");

// Supabase now issues two key formats. The old one is a JWT with a `role`
// claim; the new one is a prefixed opaque string, `sb_publishable_…` for
// the client and `sb_secret_…` for the server. Both client formats work
// as an apikey, and both server formats are catastrophic here.
const key = first("SUPABASE_ANON_KEY", "SUPABASE_PUBLISHABLE_KEY",
                  "NEXT_PUBLIC_SUPABASE_ANON_KEY");

function first(...names) {
  for (const name of names) {
    const value = (process.env[name] || "").trim();
    if (value) return value;
  }
  return "";
}

if (!url || !key) {
  if (existsSync(target)) unlinkSync(target);
  // Naming which half is missing, because "not configured" when one of
  // the two is set is a five-minute hunt through the Vercel dashboard.
  console.log(
    `building the demo, with fixtures and no backend — ${
      !url && !key ? "neither the project URL nor the key is set"
      : !url ? "the key is set but no project URL (SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL)"
      : "the project URL is set but no key (SUPABASE_ANON_KEY or SUPABASE_PUBLISHABLE_KEY)"}`,
  );
  process.exit(0);
}

// The one thing that must never happen here. A server key bypasses every
// row-level security policy in supabase/migrations, and this file is
// served to every visitor.
//
// Two checks, because one does not cover both key formats. The JWT check
// reads the `role` claim; a `sb_secret_…` key is not a JWT at all, so the
// role check cannot see it and would wave it through — which is the more
// likely mistake now, since that key sits directly above the publishable
// one in the dashboard and in the env list Vercel hands you.
if (/^sb_secret_/.test(key) || /^service_role/.test(key)) {
  console.error(
    "\nThat is a SECRET key (sb_secret_…), not a publishable one.\n\n" +
    "It bypasses row-level security and config.js is served to every\n" +
    "visitor. Refusing to write it. Use SUPABASE_ANON_KEY, or the\n" +
    "sb_publishable_… key.\n",
  );
  process.exit(1);
}

const role = readRole(key);
if (role && role !== "anon") {
  console.error(
    `\nSUPABASE_ANON_KEY holds a "${role}" key, not an anon key.\n\n` +
    "That key bypasses row-level security and config.js is public. Refusing\n" +
    "to write it. Copy the anon/public key from the project's API settings.\n",
  );
  process.exit(1);
}
if (!/^https:\/\/[^\s/]+\.supabase\.(co|in)$/.test(url) && !url.startsWith("http://localhost")) {
  console.error(`\nSUPABASE_URL does not look like a project URL: ${url}\n`);
  process.exit(1);
}

writeFileSync(target, `// Generated by tool/build-web.mjs. Do not edit, do not commit.
//
// The anon key is public by design: it identifies the project and grants
// nothing on its own. Every row it reaches is reached through the policies
// in supabase/migrations, which is where access is actually decided.
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};
`);

console.log(`wrote apps/web/config.js → ${url}`);

function readRole(jwt) {
  try {
    const [, payload] = jwt.split(".");
    return JSON.parse(Buffer.from(payload, "base64url").toString()).role || "";
  } catch {
    // Supabase has more than one key format. An unreadable key is not
    // proof of anything, so it is not a reason to fail the build — the
    // check above is a guard against an obvious mistake, not a validator.
    return "";
  }
}
